# .github/workflows/deploy.yml
name: Deploy to VPS

# Trigger this workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    # Run this job on your self-hosted runner
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Specify the Python version you use, e.g., '3.11', '3.10'
          # Using '3.x' will use a generally available Python 3 version
          python-version: '3.x'

      # Step 3: Install the 'uv' package manager
      - name: Install uv
        run: python -m pip install uv

      # Step 4: Create virtual environment using uv
      - name: Create virtual environment
        run: uv venv

      # Step 5: Install dependencies using uv
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r requirements.txt

      # Step 6: Restart the application service using systemd
      - name: Restart application service
        run: sudo systemctl restart llm-proxy.service