# .github/workflows/deploy.yml
name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install uv
        run: python -m pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r requirements.txt

      - name: Remove existing service
        run: |
          sudo systemctl stop llm-proxy || true
          sudo rm -f /etc/systemd/system/llm-proxy.service
          sudo systemctl daemon-reload

      - name: Setup systemd service
        run: |
          # Copy the service file from the repository to systemd directory
          sudo cp llm-proxy.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable llm-proxy

      # Add a step to restart the systemd service
      - name: Restart llm-proxy service
        run: |
          sudo systemctl restart llm-proxy
          sleep 2
          sudo systemctl status llm-proxy --no-pager