# .github/workflows/deploy.yml
name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install uv
        run: python -m pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r requirements.txt

      - name: Remove existing service
        run: |
          sudo systemctl stop llm-proxy || true
          sudo rm -f /etc/systemd/system/llm-proxy.service
          sudo systemctl daemon-reload

      - name: Setup systemd service
        run: |
          sudo bash -c 'cat <<EOF > /etc/systemd/system/llm-proxy.service
          [Unit]
          Description=LLM Proxy FastAPI Service
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory=$PWD
          ExecStart=$PWD/.venv/bin/python -m uvicorn proxy:app --host 0.0.0.0 --port 8000
          Restart=always
          RestartSec=3
          User=$(whoami)
          Environment=PYTHONUNBUFFERED=1

          [Install]
          WantedBy=multi-user.target
          EOF'
          
          sudo systemctl daemon-reload
          sudo systemctl enable llm-proxy

      # Add a step to restart the systemd service
      - name: Restart llm-proxy service
        run: |
          sudo systemctl restart llm-proxy
          sleep 2
          sudo systemctl status llm-proxy --no-pager